# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-13 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', tinymce.models.HTMLField(verbose_name='文章内容')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论编号')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('art_cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='评论文章')),
                ('null', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('cusID', models.CharField(max_length=20)),
                ('header', models.ImageField(blank=True, default='static/headers/xxx.jpg', null=True, upload_to='static/headers/')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user_cont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User', verbose_name='用户评论'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='blog.User', verbose_name='作者'),
        ),
    ]
