# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-27 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('usermanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='users',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
