# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-25 02:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recv_name', models.CharField(max_length=100, verbose_name='收货人')),
                ('recv_tel', models.CharField(max_length=20, verbose_name='收获人电话')),
                ('province', models.CharField(max_length=100, verbose_name='收获人省份')),
                ('city', models.CharField(max_length=100, verbose_name='收获人城市')),
                ('area', models.CharField(max_length=100, verbose_name='收获人县区')),
                ('street', models.CharField(max_length=255, verbose_name='收获人街道')),
                ('desc', models.CharField(max_length=255, verbose_name='详细地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='地址所属用户')),
            ],
        ),
    ]
