# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-18 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', tinymce.models.HTMLField(verbose_name='文章内容')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=20)),
                ('cusID', models.CharField(max_length=20)),
                ('header', models.ImageField(blank=True, default='static/headers/xxx.jpg', null=True, upload_to='static/headers/')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='user.Users', verbose_name='作者'),
        ),
    ]
