# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-05 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论编号')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('art_cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Article', verbose_name='评论文章')),
                ('null', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Comment', verbose_name='评论')),
                ('user_cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users', verbose_name='用户评论')),
            ],
        ),
    ]
