# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-11 02:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recv_name', models.CharField(max_length=100, verbose_name='收货人')),
                ('recv_tel', models.CharField(max_length=20, verbose_name='收货人电话号码')),
                ('province', models.CharField(max_length=100, verbose_name='收货人的省份')),
                ('city', models.CharField(max_length=100, verbose_name='收货人的城市')),
                ('area', models.CharField(max_length=100, verbose_name='收货人的县区')),
                ('desc', models.CharField(max_length=255, verbose_name='详细地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否是默认地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='地址的所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50, verbose_name='用户名称')),
                ('age', models.IntegerField(default=18, verbose_name='用户年龄')),
                ('gender', models.IntegerField(default=1, verbose_name='用户性别')),
                ('header', models.ImageField(default='static/images/headers/default.jpg', upload_to='static/images/headers/', verbose_name='用户头像')),
                ('email', models.CharField(default='123456@qq.com', max_length=100, verbose_name='用户邮箱')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
